#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")

apiVersion: v1
kind: Secret
metadata:
  name: pws-service-broker
  namespace: pws-service-broker
type: Opaque
data:
  cf_api: #@ base64.encode(data.values.cf_api)
  cf_username: #@ base64.encode(data.values.cf_username)
  cf_password: #@ base64.encode(data.values.cf_password)
  cf_organization_guid: #@ base64.encode(data.values.cf_organization_guid)
  cf_space_guid: #@ base64.encode(data.values.cf_space_guid)
